site:
  title: nREPL
  url: https://nrepl.org/
  start_page: nrepl::index.adoc
content:
  sources:
  - url: https://github.com/nrepl/nREPL.git
    branches: []
    tags: ['0.*', '!0.0.*', '!0.3.*', '!0.4.0', '!0.4.1', '!0.4.2', '!0.4.3', '!0.4.4',  '!0.4.5']
    start_path: doc
asciidoc:
  attributes:
    linkattrs: ''
    toc: ~
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  clean: true
  dir: ./docs
